### ISSUE TITLE
Got error in a .css file with some tailwind

### ISSUE THREAD

**Issue by t1gu1** [luckasRanarison/tailwind-tools.nvim#16]
**Describe the bug**
In a `.css` file, I got an error.

Here is what it looks like:
![image](https://github.com/luckasRanarison/tailwind-tools.nvim/assets/12479055/160f5a18-378f-44f0-aefd-1fe2f112eebf)

P.S. That's not my way of using tailwind.. This is just a project that I have to works with..

**To Reproduce**
1. Go to a `.css` file using some tailwind.
2. Add a space, delete a caracter or paste something (It trigger the error on each action everytime)
3. See error trigger at every action of the step 2

Here is a small example of what a .css with tailwind can contain.

```css
body {
    @apply flex min-h-[100svh] flex-col bg-skin-fill font-mono text-skin-base
    selection:bg-skin-accent selection:bg-opacity-70 selection:text-skin-inverted;
  }
  section,
  footer {
    @apply mx-auto max-w-3xl px-4;
  }
  a {
    @apply outline-2 outline-offset-1 outline-skin-fill
    focus-visible:no-underline focus-visible:outline-dashed bg-red-600;
  }
  svg {
    @apply inline-block h-6 w-6 fill-skin-base group-hover:fill-skin-accent;
  }
```

**Expected behavior**
Just doing nothing in a first time? 
Maybe it should not try to conceal in that type of file? (At least in a first time if it's hard to fix)

**More information**

The color thing works in that type of file but it's weird with the actual conceal.

When cursor isn't on the line: (It conceal it?)
![image](https://github.com/luckasRanarison/tailwind-tools.nvim/assets/12479055/28f84384-34be-47b0-8a8d-53f090029fc9)

When cursor is on the line: (It disable the conceal)
![image](https://github.com/luckasRanarison/tailwind-tools.nvim/assets/12479055/6be476ad-3eec-4aaf-ae0e-572c78015f49)

**Environment (please complete the following information):**
 - Operating system: Mac OS Sonoma 14.2.1
 - Neovim version or commit: 0.10.0
 - Nvim-treesitter commit: 5e4f959 (Updated yesterday, using master)
 - tailwind-language-server version: 0.0.16
